name: Daily Signals

on:
  schedule:
    - cron: '0 9 * * 1-5'   # 工作日 UTC 09:00 = 北京时间 17:00
  workflow_dispatch:

jobs:
  run-signals:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tushare pandas numpy

      - name: Run script
        env:
          TUSHARE_TOKEN: ${{ secrets.TUSHARE_TOKEN }}
        run: |
          python calc_signals.py

      - name: Upload signals
        uses: actions/upload-artifact@v4
        with:
          name: today-signals
          path: data/today_signals.csv
