name: Daily Signals

on:
  # 每周一到周五运行两次：UTC 09:30 和 10:10（对应北京时间 17:30 和 18:10）
  schedule:
    - cron: '30 9 * * 1-5'
    - cron: '10 10 * * 1-5'
  # 允许手动触发
  workflow_dispatch:

# 回写 CSV 到仓库需要写权限
permissions:
  contents: write

jobs:
  run-signals:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tushare pandas numpy akshare

      - name: Run script
        env:
          TUSHARE_TOKEN: ${{ secrets.TUSHARE_TOKEN }}
        run: |
          python calc_signals.py

      - name: Commit CSV back to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/today_signals.csv
          git commit -m "update signals: $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "no changes"
          git push

      - name: Upload signals
        uses: actions/upload-artifact@v4
        with:
          name: today-signals
          path: data/today_signals.csv
